service:
  name: ${self:custom.path}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  path: auth
  serverless-offline:
    port: 5001
    prefix: api/${self:custom.path}

provider:
  profile: ${opt:profile, 'tpip'}
  name: aws
  region: eu-west-2
  stage: api
  runtime: nodejs6.10

functions:
  users:
    handler: users/handler.list
    events:
      - http:
          method: get
          path: users/list
